#!/usr/bin/env node
/**
 * agent-tester/report.mjs
 * Generate a readable markdown report from scored results.
 *
 * Usage:
 *   node report.mjs --results results/run-...-scored.json
 *   node report.mjs --results results/run-...-scored.json --open
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { execSync } from 'node:child_process';

const args = process.argv.slice(2);
const get = (flag) => { const i = args.indexOf(flag); return i >= 0 ? args[i+1] : null; };
const resultsPath = resolve(get('--results') || '');
const doOpen = args.includes('--open');

if (!resultsPath) { console.error('--results required'); process.exit(1); }

const run = JSON.parse(readFileSync(resultsPath, 'utf8'));

// Aggregate scores
const modelMap = {};
for (const { results } of run.scored || []) {
  for (const r of results) {
    if (!modelMap[r.model]) modelMap[r.model] = { label: r.label, scores: [], latencies: [], results: [] };
    modelMap[r.model].results.push(r);
    if (r.judgment?.score != null) {
      modelMap[r.model].scores.push(r.judgment.score);
      modelMap[r.model].latencies.push(r.latency || 0);
    }
  }
}

const avg = arr => arr.length ? arr.reduce((a, b) => a + b, 0) / arr.length : 0;
const sorted = Object.values(modelMap).sort((a, b) => avg(b.scores) - avg(a.scores));

const date = new Date(run.timestamp).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

let md = `# Agent Test Report
**Agent:** ${run.agent.split('/').slice(-1)[0]}  
**Date:** ${date}  
**Judge:** ${run.judge || 'unscored'}  
**Test cases:** ${run.cases?.length || 0}  
**Models tested:** ${sorted.length}

---

## 🏆 Leaderboard

| Rank | Model | Avg Score | Avg Latency |
|------|-------|-----------|-------------|
`;

sorted.forEach((m, i) => {
  const score = avg(m.scores).toFixed(2);
  const latency = Math.round(avg(m.latencies));
  md += `| ${i+1} | ${m.label} | **${score}/10** | ${latency}ms |\n`;
});

md += `\n---\n\n## 📋 Per-Case Results\n\n`;

for (const { case: tc, results } of (run.scored || [])) {
  md += `### ${tc.name || tc.id}\n\n`;
  md += `**Input:** ${tc.user_message?.slice(0, 120)}...\n\n`;

  const valid = results.filter(r => r.judgment?.score != null).sort((a, b) => b.judgment.score - a.judgment.score);

  if (valid.length === 0) {
    md += `*All models errored on this case.*\n\n`;
    continue;
  }

  // Top 3 outputs in full
  for (const r of valid.slice(0, 3)) {
    const rank = valid.indexOf(r) + 1;
    const emoji = ['🥇', '🥈', '🥉'][rank - 1] || `#${rank}`;
    md += `#### ${emoji} ${r.label} — ${r.judgment.score}/10\n\n`;
    md += `**Breakdown:** Voice: ${r.judgment.breakdown?.voice_accuracy ?? '?'} | Format: ${r.judgment.breakdown?.format_compliance ?? '?'} | Specificity: ${r.judgment.breakdown?.specificity ?? '?'} | Hook: ${r.judgment.breakdown?.hook_quality ?? '?'}\n\n`;
    if (r.judgment.best_line) md += `**Best line:** *"${r.judgment.best_line}"*\n\n`;
    if (r.judgment.worst_issue && r.judgment.worst_issue !== 'none') md += `**Issue:** ${r.judgment.worst_issue}\n\n`;
    md += `**Output:**\n\`\`\`\n${r.output}\n\`\`\`\n\n`;
  }

  // Rest as compact table
  if (valid.length > 3) {
    md += `<details><summary>Other models (${valid.length - 3})</summary>\n\n`;
    md += `| Model | Score | Issue |\n|-------|-------|-------|\n`;
    for (const r of valid.slice(3)) {
      md += `| ${r.label} | ${r.judgment.score}/10 | ${r.judgment.worst_issue || '-'} |\n`;
    }
    md += `\n</details>\n\n`;
  }
}

md += `---\n\n## 💡 Recommendation\n\n`;
const winner = sorted[0];
const runnerUp = sorted[1];
if (winner) {
  md += `**Winner: ${winner.label}** (${avg(winner.scores).toFixed(2)}/10)\n\n`;
  if (runnerUp && avg(winner.scores) - avg(runnerUp.scores) < 0.5) {
    md += `Close race with **${runnerUp.label}** (${avg(runnerUp.scores).toFixed(2)}/10) — consider latency and cost as tiebreaker.\n\n`;
  }
}

md += `\n*Generated by agent-tester at ${new Date().toISOString()}*\n`;

const outPath = resultsPath.replace('-scored.json', '-report.md').replace('.json', '-report.md');
writeFileSync(outPath, md);
console.log(`Report saved: ${outPath}`);

if (doOpen) execSync(`open ${outPath}`);
